version: '3.9'

services:
  java-app:
    container_name: java-app
    image: kdp/java-spring-app:1.0.0
    build:
      context: .
      dockerfile: DockerfileGradle # DockerfileGradle  # or DockerfileMaven
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://pg-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - pg-db
    healthcheck:
      test: [ "CMD-SHELL", "curl  http://localhost:8080/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      
  pg-db:
    container_name: pg-db
    image: postgres:12
    ports:

      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  karate:
    container_name: karate
    image: karate
    build:
      context: .
      dockerfile: DockerfileKarate
    volumes:
      - ./karate-reports:/target/karate-reports
    depends_on:
      java-app:
        condition: service_healthy
    command: ["java", "-jar", "karate.jar", "src/test/java/user/user.feature"]

volumes:
  pgdata: {}
