name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
#    runs-on: ubuntu-latest # Running on ubuntu-latest (GitHub-hosted runner)
    runs-on: self-hosted  # Running on self hosted runner (Azure VM)
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # Install Java on the self-hosted runner (Not needed for github-hosted runner)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Docker and docker-compose on the self-hosted runner (Not needed for github-hosted runner)
      - name: Install Docker and docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Run docker compose
        run: sudo docker-compose -f ./docker-compose.yml up --abort-on-container-exit  # --abort-on-container-exit flag. This flag will stop all containers if any container was stopped.

      - name: Copy the junit html reports from the container to the host
        run: sudo docker cp java-app:/app/build/reports/tests/test-internal /tmp/junit-html-reports

      - name: Archive Karate test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: karate-reports/

      - name: Archive JUnit HTML test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-html-reports
          path: /tmp/junit-html-reports/