name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

#      - name: junit html test directoriy
#        run: mkdir -p /tmp/junit-html-reports
#
#      - name: Cache Docker layers
#        uses: actions/cache@v3
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-
#
#      - name: Build and run Docker Compose
#        run: |
#          docker-compose up -d --build
#        env:
#         PWD: ${{ github.workspace }}  #set the PWD environment variable to the GitHub workspace directory

      - name: Collect and print logs for all Docker containers
        run: docker compose logs

      - name: Copy the junit html reports from the container to the host
        run: docker cp java-app:/app/build/reports/tests/test-internal /tmp/junit-html-reports

      - name: Check karate-reports directory and print contents # For debugging purposes
        run: |
          if [ -d "./karate-reports" ]; then
            echo "karate-reports directory exists. Contents:"; ls -la ./karate-reports
            echo "workspace  directory : $PWD"
            echo "Absolute path of karate-reports directory:"; realpath ./karate-reports
          else
            echo "karate-reports directory does not exist."
            echo "workspace  directory: $PWD"
            echo "Absolute path of karate-reports directory:"; realpath ./karate-reports
          fi

      - name: Archive Karate test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: karate-reports/

      - name: Archive JUnit HTML test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-html-reports
          path: /tmp/junit-html-reports/